# Site settings
title: Sam J Sharpe
url: http://www.samsharpe.net
description: "Dog Lover, Imperfect Husband, IT Architect and Linux Engineer in London, UK"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#3D3D3D'
  links: '#66CCFF'

# Footer settings
footer: Sam J Sharpe

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SamJSharpe
  - title: facebook
    url: https://www.facebook.com/samsharpe
  - title: linkedin
    url: https://www.linkedin.com/in/samsharpe
  - title: github
    url: https://github.com/SamJSharpe
  - title: mastodon
    url: https://mastodon.social/@SamJSharpe

# Build settings
permalink: pretty

gems:
  - jekyll-feed
